from enum import Enum


class ActionType(str, Enum):
    FILE_CREATE = "FILE_CREATE"
    FILE_DELETE = "FILE_DELETE"
    FILE_MODIFY = "FILE_MODIFY"
    FILE_MOVE = "FILE_MOVE"
    REGISTRY_CREATE = "REGISTRY_CREATE"
    REGISTRY_MODIFY = "REGISTRY_MODIFY"
    REGISTRY_DELETE = "REGISTRY_DELETE"
    PROCESS_LAUNCH = "PROCESS_LAUNCH"
    PROCESS_TERMINATE = "PROCESS_TERMINATE"
    TASK_CREATE = "TASK_CREATE"
    TASK_MODIFY = "TASK_MODIFY"
    TASK_DELETE = "TASK_DELETE"
    DOWNLOAD = "DOWNLOAD"
    CONFIG_MODIFY = "CONFIG_MODIFY"


class VerificationDecisionEnum(str, Enum):
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"
    ESCALATE = "ESCALATE"


class EvidenceType(str, Enum):
    FILESYSTEM = "FILESYSTEM"
    REGISTRY = "REGISTRY"
    PROCESS = "PROCESS"
    TASK = "TASK"
    DOWNLOAD = "DOWNLOAD"
    CONFIGURATION = "CONFIGURATION"


class ValidationStatus(str, Enum):
    PENDING = "PENDING"
    VALID = "VALID"
    INVALID = "INVALID"
    INCOMPLETE = "INCOMPLETE"


class SideEffectSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SideEffectSurface(str, Enum):
    FILESYSTEM = "FILESYSTEM"
    REGISTRY = "REGISTRY"
    PROCESS = "PROCESS"
    NETWORK = "NETWORK"
    PERSISTENCE = "PERSISTENCE"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class VerifierID(str, Enum):
    FILESYSTEM = "FILESYSTEM"
    REGISTRY = "REGISTRY"
    PROCESS = "PROCESS"
    TASK = "TASK"
    DOWNLOAD = "DOWNLOAD"
    CONFIGURATION = "CONFIGURATION"
    SIDE_EFFECT = "SIDE_EFFECT"
    DRIFT = "DRIFT"


class ReviewDecision(str, Enum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    FURTHER_INVESTIGATION = "FURTHER_INVESTIGATION"


class ChainIntegrityStatus(str, Enum):
    HEALTHY = "HEALTHY"
    GAP_DETECTED = "GAP_DETECTED"


class EvidenceResolutionStatus(str, Enum):
    RESOLVED = "RESOLVED"
    UNRESOLVED = "UNRESOLVED"
    EXPIRED = "EXPIRED"
